Repository dsccommunity/CertificateDsc, pull requests merged in 2018-05, with the labels that each got.

#130 PfxImport - Enable Re-import if Private Key not installed - Fixes #129
  CHANGELOG.md
  Modules/CertificateDsc/DSCResources/MSFT_PfxImport/MSFT_PfxImport.psm1
  Modules/CertificateDsc/DSCResources/MSFT_PfxImport/en-US/MSFT_PfxImport.strings.psd1
  Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1
  Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1
  Tests/Unit/CertificateDsc.Common.Tests.ps1
  Tests/Unit/MSFT_PfxImport.Tests.ps1
Labels: waiting for the author

#133 Fix Merge Issue in CHANGELOG.MD from PR #130
  CHANGELOG.md
Labels: needs review

#108 Test-Thumbprint: Check for FIPS
  CHANGELOG.md
  Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1
  Tests/Unit/CertificateDsc.Common.Tests.ps1
Labels: waiting for author response
